/* Database schema to keep the structure of entire database. */

-- animals

CREATE TABLE animals (
  id int GENERATED BY DEFAULT AS IDENTITY,
  name varchar,
  date_of_birth date,
  escape_attempts int,
  neutered boolean,
  weight_kg float
);

ALTER TABLE animals
ADD species varchar;

ALTER TABLE animals
DROP COLUMN species;

ALTER TABLE animals
ADD species_id int;

ALTER TABLE animals
ADD FOREIGN KEY (species_id)
REFERENCES species (id);

ALTER TABLE animals
ADD owner_id int;

ALTER TABLE animals
ADD FOREIGN KEY (owner_id)
REFERENCES owners (id);

-- owners

CREATE TABLE owners (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fulll_name varchar,
  age int
);

-- species

CREATE TABLE species (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);