/* Database schema to keep the structure of entire database. */

-- animals

CREATE TABLE animals (
  id int GENERATED BY DEFAULT AS IDENTITY,
  name varchar,
  date_of_birth date,
  escape_attempts int,
  neutered boolean,
  weight_kg float
);

ALTER TABLE animals
ADD PRIMARY KEY (id);

ALTER TABLE animals
ADD species varchar;

ALTER TABLE animals
DROP COLUMN species;

ALTER TABLE animals
ADD species_id int;

ALTER TABLE animals
ADD FOREIGN KEY (species_id)
REFERENCES species (id);

ALTER TABLE animals
ADD owner_id int;

ALTER TABLE animals
ADD FOREIGN KEY (owner_id)
REFERENCES owners (id);

-- owners

CREATE TABLE owners (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fulll_name varchar,
  age int
);

CREATE INDEX owner_email_asc ON owners(email);

-- species

CREATE TABLE species (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

-- vets

CREATE TABLE vets (
  id int GENERATED BY DEFAULT AS IDENTITY,
  name varchar,
  age int,
  date_of_graduation date
  PRIMARY KEY(id)
);

-- relationships

-- vets

CREATE TABLE specializations (
  species_id int,
  vets_id int,
  PRIMARY KEY(species_id, vets_id),
  CONSTRAINT fk_species_rel
    FOREIGN KEY (species_id)
    REFERENCES species (id),
  CONSTRAINT fk_vets_rel
    FOREIGN KEY (vets_id)
    REFERENCES vets (id)
);

-- visits

CREATE TABLE visits (
  id int GENERATED BY DEFAULT AS IDENTITY,
  animal_id int,
  vets_id int,
  date_of_visit date,
  PRIMARY KEY(id),
  CONSTRAINT fk_animal_rel
    FOREIGN KEY (animal_id)
    REFERENCES animals (id),
  CONSTRAINT fk_vets_rel
    FOREIGN KEY (vets_id)
    REFERENCES vets (id)
);

CREATE INDEX visits_animal_asc ON visits(animal_id);

CREATE INDEX visits_vets_asc ON visits(vets_id);
