/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
  id int GENERATED BY DEFAULT AS IDENTITY,
  name varchar,
  date_of_birth date,
  escape_attempts int,
  neutered boolean,
  weight_kg float
);

ALTER TABLE animals
ADD species varchar;